name: Azure deployment
on:
  workflow_dispatch:

env:
  OUTPUT_PATH: ${{ github.workspace }}/output
  AZURE_APP_NAME: ScoopSearch.Functions
  APP_PATH: ${{ github.workspace }}/src/ScoopSearch.Functions/
  # AZURE_FUNCTIONAPP_PUBLISH_PROFILE: '' # Secret in the repository
  DOTNET_VERSION: '6.0.x'

jobs:
  deployment-skipped:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
    - name: Message
      run: echo "Deployment skipped. Only main branch can be deployed."

  deployment:
    name: Deployment ðŸš€ðŸŒ
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Full history is required by GitVersion

    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'

    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15

    - name: Install dependencies
      run: dotnet restore ${{ env.APP_PATH }} --verbosity detailed

    - name: Publish
      run: >
        dotnet publish ${{ env.APP_PATH }}
        --configuration Release
        --no-restore
        --output ${{ env.OUTPUT_PATH }}
        -p:Version=${{ steps.gitversion.outputs.AssemblySemVer }}
        -p:FileVersion=${{ steps.gitversion.outputs.AssemblySemFileVer }}
        -p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }}
        --verbosity detailed

    - name: Deploy to Azure
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_APP_NAME }}
        package: '${{ env.OUTPUT_PATH }}'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: function-app
        path: ${{ env.OUTPUT_PATH }}
